sudo: required
language: java
jdk: oraclejdk8
services:
- docker
env:
  global:
  - secure: "dH9jCl/0tCzQaDbMnIqCsLIDh5P3k1e6Y1qOnaIkgTma2bSQ4Ph1O8F0SNPN4c+Wpn71IM8L/29L11qh9odGahxJb6jl4uJFeOEi9kxqjp8EMFClnjKhgBQ4b3pfb/J1TKDAGZm8h8UgBBXhmk4iRjk+bYhaGLBtZWOlf+/vZMWE8luG0P9ype2hyfqSmNQTrjygFG2bp15QfMDZZ4ORvrekHn7N0fm+F1YgXMzZDB0aUmLnI8NpcGfgucGojPyWqpDIAcxZ7gDwv92NJNZEQ3NLgNAkEzLoO7WwzQd9To+z5bCoDy00anEkIdARYmIslQgWt1sUR4XfeoMalJu2v/i9u4FHjfBnma52BYWo4ExpRu/l8ulcXGL2ynjPn2noMAs2K+WT2CSXWqGowOWKz9JgO32Xd6EFQqTSS49WomzmO4FVHkuH/zzNS3kuImHmm1qno8tgrcSTchF80AZtNBjPU8E/ka7edwSw0+jU47mrbRoxavJwpq35L2FQaQld/aDjnxybjlz3hY11vRLQOXA1f/vQcdp9dkqEwMgHVIh5LU7GaQ3TYAND3iQoWSmBpCrbcbOvP6D2OAHz8VRhOnJQlnH6NxreJgwshAUMGooKMSz5sRsFUK6blVz9U8ysf1Ecp1zbqxRsCiDj1jyGxdiZMl81ihrTwpJrNThG+2o="
  - secure: "DPT7ReBhVn68FT5hRzOH45kfbUfqrhh1cyUmkvgY4ddatN+0l8goV8B8JUIk6U+JL0rplJXCSJCP25l9sDQ5a1S08LNvyE0hRzKteLQ7frvs+DGdevCpYKgfLx+mOfUQ068ZjRwxA3P9haESDVjk9s58SET9h+8buWBrK1vJlwjqH5bPGBp/4Hc/RKWqy3TR/igaJJeasmNGQH4VN38Qrdsu7uIawuBg1YtDU9loZSkAz1hM7mgdgaS1eVUejV0nvzPkfper1MSmzpq12KJPPe3cOHwKyebS/vgbLf75cJ1UsdI8BTBlOyaES6t0mi+CKs79sLpw/8iKs4QTRddqoZdvC9Y+05yPxaFX4GSV+7F8bw4AULShNazZRfuX83mEoDZv5OSvZEAjCCwXOSOy5B620MRXzaAGWP6jyk0lXDzxfTCN1Pupi5cX1M/VNd74rPTPLAB6V1XAX3o7x+N1eNYQ9WWKzkKQKwN/AG3dtitemgV1rUFDgDY1gfaeqDmAKT2PTNU6t4+NVeEWixwUyL7RrY5gPFYLWJYkAXauazB0I6u2J5glDKNa0Oufet6iUBRFXbXgZXUUKJQujaebGv8JenLlJF1huZcTSauSvLFW1oQo4lqJDyBWhs3OVxIv97OFdM6yHr26J2ylosLFEgfGSiHWrf0DSE9FrB3vl3M="
  - secure: "gzFqxzYXWb7DwkmIglA36TmOtErPagmsqyT5w2Lreh4p+9l7Oz7lRis91i7YxTyBvp/ZulAIB0c11qftv3Ycg6ofDvj/NN+f4XpLssKN7xJOz9FAHlNJ1gzs7P4c6Qu4FiGKBJqBCcoYhK/oFhLpR+u/cEuyXwG706nJemZVevHeJIjGbl1XNbD/1MN1LGisP1YnIRQLs4uHsSBRDN3aWNxYuRMgsFvD1+m7W9qQ8w6kTFhU2FYvlexrStMITDyROnza8nBncDmrVUWVAXpMyGsWGZHe3zHOEVpZul4c2LJA++Mehv9PeHicQ0epfwxIAUpsO44NKci54poJd3gdQQux/ki4coylr0VeShoe15G1Q+mCkZa/nU6hJKb+42kJGBZJSHhQJnd0GqBuTpeDH8dKLcknpOgp5uZ9Hq6LSD6Nu7iDJRn4JeXrxEqWqJm4nUCSVtUQQydlXFCRSg8AlEOQ0tCLDgLblULlhcWhP5gSVl3ldMOJeSaEcHSkQz/dFAZmqnz2f9lROSj8wyT6JSOmDf6wQcAASk4sSj/t5++ETyBCkwgtMrtxaL4TZgYHZ8jnvJmrX5UXQp6ghboWnrVARfZSKPUGfZKl5DTrBcX+K0RpAOBmkml9ojahQ+ZghfK2ViPPH4ldBB/mwpETjj4Ivyv/PFkxECeijSwPYH8="
  - secure: "EZS4c0oEDP6yavGY+zMf9uKRREfFVaMU6WGrcLEmAEushYC/4ND86kVTRldaw0vkdn27dlmCsBh9NyEHokjiBBNrgvVkCoRFtqEzGzv/cD9HKBoxQtnpqz1wxD0kSOv0GGZQjgXYQcuCUzDmEm0VOlVs/QK3UQhcJwG8RXSJn3VIyJAWJGqJfXBmuOgM+XqSciTwNPEpc0cvXZFTP49xb621o4NRupW7LoterfjKKIyjwQK2kF+w+3DC0IssTzqpjF9C8AOKFZqFS4cdw9mP3ToYzA+XX5f3SSFoRAqi3GG8G1f1rcPwz0hpO/byMuF4Nydh6MlGebKYFL1JApen/0NRl0QwepKU0DhCqoWOV3D8s37cDEWZHO4lkOK1IcCgJaCZy1OHKE2CMA8bgwbYciPdPpBX4YYTwV2ejNAASIkI2BqAAPRZuFY9o/jkrPZrw9B+KCmJyoRDn9iKSeDOUQ3wQSdMokpEtDjDTSXmsYSZ/ArsEAtcA7OY8GtrEtB6uEs9Xy2/RI3llD3c9MYwYZqOXVWZ3y9ThoFvkLur2/9VLbELCI/HJGbWTtOjLaQAgfta+1KyAGAfUxTHO1ujBTpp114PMo2hihcc8XONbq+m9q4PAxhPdPXySt4Zo2egiRiWDwl5SdRY8niG2UaG/D14yE6nXsZ2nlDZnUV88Ss="
  - COMMIT=${TRAVIS_COMMIT::7}
addons:
  sonarcloud:
    organization: "nitesh009-github"
    token:
      secure: $SONAR_TOKEN

script:
- ./mvnw clean install -B
- ./mvnw clean org.jacoco:jacoco-maven-plugin:prepare-agent


cache:
  directories:
  - '$HOME/.m2/repository'
  - '$HOME/.sonar/cache'


after_success:
- docker login -u $DOCKER_USER -p $DOCKER_PASS
- export TAG=`if [ "$TRAVIS_BRANCH" == "master" ]; then echo "latest"; else echo $TRAVIS_BRANCH
  ; fi`
- export IMAGE_NAME=nitesh009/spring-boot
- docker build -t $IMAGE_NAME:$COMMIT .
- docker tag $IMAGE_NAME:$COMMIT $IMAGE_NAME:$TAG
- docker push $IMAGE_NAME

#
#deploy:
 # provider: heroku
  # api_key: $HEROKU_API_KEY
  # app: nk-spring-boot-app
