version: '2'
services:
  springbootapp:
    build: .
    ports:
      - "18080:8080"
      - "18787:8787"
    depends_on:
      - fk-db

  fk-db:
    image: postgres
    container_name: fkdb
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: fk
